# Generated by Django 6.0.2 on 2026-03-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='remaining_quantity',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
