# Generated by Django 6.0.2 on 2026-03-01 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockentry_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
