# Generated by Django 6.0.2 on 2026-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockexit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
