# Generated by Django 6.0.2 on 2026-03-01 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockentry_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
