# Generated by Django 6.0.2 on 2026-03-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_supplier'),
        ('stock', '0005_alter_stockentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.supplier'),
        ),
    ]
