# Generated by Django 6.0.2 on 2026-03-02 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockentry_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexit',
            name='authorized_by',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockexit',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockexit',
            name='reason',
            field=models.CharField(choices=[('sale', 'Vente'), ('loss', 'Perte'), ('damage', 'Produit endommagé'), ('adjustment', 'Ajustement')], max_length=20),
        ),
    ]
