# Generated by Django 6.0.2 on 2026-03-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('perishable', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('management_method', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
