# Generated by Django 6.0.2 on 2026-03-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='selling_price',
        ),
    ]
