# Generated by Django 6.0.2 on 2026-03-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_minimum_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
