# Generated by Django 6.0.2 on 2026-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='management_method',
            field=models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO')], default='FIFO', max_length=10),
        ),
    ]
