# Generated by Django 6.0.2 on 2026-03-01 04:09

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('etablissement', 'Etablissement'), ('societe', 'Societe')], max_length=20)),
                ('sub_type', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(max_length=150)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('province', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
