# Generated by Django 6.0.2 on 2026-03-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('BIF', 'Franc Burundais (BIF)'), ('USD', 'Dollar Americain (USD)'), ('EUR', 'Euro (EUR)'), ('CDF', 'Franc Congolais (CDF)')], default='CDF', max_length=10),
        ),
    ]
