# Generated by Django 6.0.2 on 2026-03-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companie', '0003_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
