# Generated by Django 6.0.2 on 2026-03-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companie', '0004_company_address_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/company_logo/'),
        ),
    ]
