# Generated by Django 6.0.2 on 2026-03-05 06:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companie', '0006_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
