# Generated by Django 6.0.2 on 2026-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
