# Generated by Django 6.0.2 on 2026-03-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companie', '0001_initial'),
        ('finance', '0002_cashier_is_active_cashier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoperation',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.cashier'),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companie.company')),
            ],
        ),
        migrations.AddField(
            model_name='cashier',
            name='cash_registers',
            field=models.ManyToManyField(blank=True, null=True, related_name='cashiers', to='finance.cashregister'),
        ),
        migrations.AddField(
            model_name='cashoperation',
            name='cash_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.cashregister'),
        ),
    ]
