# Generated by Django 6.0.2 on 2026-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_cashoperation_cashier_cashregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='cash_registers',
            field=models.ManyToManyField(blank=True, related_name='cashiers', to='finance.cashregister'),
        ),
    ]
