# Generated by Django 6.0.2 on 2026-03-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'En cours'), ('completed', 'Finalisée')], default='draft', max_length=20),
        ),
    ]
