# Generated by Django 6.0.2 on 2026-03-02 04:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_before_tax',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
