# Generated by Django 6.0.2 on 2026-03-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashier_is_active_cashier_phone'),
        ('sale', '0003_remove_sale_discount_remove_sale_total_before_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='finance.cashier'),
        ),
    ]
