# Generated by Django 6.0.2 on 2026-03-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_cashoperation_cashier_cashregister_and_more'),
        ('sale', '0004_alter_sale_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cashregister'),
        ),
    ]
