# Generated by Django 6.0.2 on 2026-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_sale_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='validated_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
